version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: deployment/Dockerfile
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=lecture-docker-starter
    ports:
      - "4001:4001"
    depends_on:
      - database
  web:
    build:
      context: ./frontend
      dockerfile: deployment/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=lecture-docker-starter
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
